version: "3.8"

services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tracking_map
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
